### ISSUE TITLE
Not all fields are displayed on create form

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/prisma-admin-feedback#121]
Not all fields are displayed on create form.

![Screenshot 2019-04-08 at 11 45 04](https://user-images.githubusercontent.com/37446141/55829754-1cadb680-5b18-11e9-8f53-f59040481c9d.png)

Versions:
 - Connector: Postgres
 - Prisma Server: 1.30.0
 - `prisma` CLI: prisma/1.30.0 (linux-x64) node-v10.15.0
 - OS: CentOS Linux 7 
 - other dependencies: prisma-client

**Comment by madebysid** [comment]
@vadim-shilov @pantharshit00 I was able to see this as well, we'll have a fix out soon!

**Comment by madebysid** [comment]
We've just released a new version that should fix this.

Unfortunately, this is a breaking change, so you'd have to re-deploy your service using `prisma deploy` again.
If you run into issues, you can read more about the release and the changes [here](https://www.prisma.io/blog/datamodel-v11-lrzqy1f56c90)

**Comment by Nedomas** [comment]
Just wanted to followup to check if fields named `type` now should show up in the admin? I'm on datamodel v1.1 right now, but it still looks like the `type` field is not visible in the edit panel for me.

**Comment by madebysid** [comment]
@Nedomas They should now. Have you also been using v1.31+ of the Docker image? If you're using the demo servers, you should be good to go already.

**Comment by Nedomas** [comment]
@madebysid I can confirm that I am on v1.31.0 (Heroku) and am still missing the `type` field.

<img width="580" alt="Screenshot 2019-05-01 at 19 59 51" src="https://user-images.githubusercontent.com/1877286/57029884-b0702f80-6c4b-11e9-9c65-0ec4f3b0cd81.png">
