### ISSUE TITLE
Prisma Console is not allowing me to add permissions to a user

### ISSUE THREAD

**Issue by WebRuin** [prisma/prisma-admin-feedback#124]
I am trying to add permissions to a user in the Prisma Console.  And here are the steps I  am trying to take.

1. I click the three dots next to above and to the right of the permissions field
2. I click "Add an item"
3. I click and choose the permission I want
4. I see "1 Unconfirmed change"
5. I click "Save to draft"
6. I notice nothing changed.

This is in my schema.graphql
```
type User {
  id: ID!
  name: String!
  email: String!
  permissions: [Permission!]!
}
```

This is the enum for my USER
```
enum Permission {
  ADMIN
  USER
  BATHROOMCREATE
  BATHROOMUPDATE
  BATHROOMDELETE
  PERMISSIONUPDATE
}
```
I have combed through my code a hundred times and see no bugs that would cause this.
Please help or fix this if it is a bug.

This may also help: [Prisma Forum Thread on this topic](https://www.prisma.io/forum/t/i-can-not-update-a-dev-users-permissions-in-prisma-web-console/6569/11)

**Comment by WebRuin** [comment]
Confussed

**Comment by madebysid** [comment]
Hi @WebRuin, we've just a released a new version where I can't seem to reproduce this, which leads me to believe this should be fixed now.

Unfortunately, this is a breaking change, so you'd have to re-deploy your service using `prisma deploy` again. If you run into issues, you can read more about the release and the changes [here](https://www.prisma.io/blog/datamodel-v11-lrzqy1f56c90)

Can you let me know after if you still see this?

**Comment by WebRuin** [comment]
1) I updated my syntax and added the new required fields:
```
enum Permission {
  ADMIN
  USER
  BATHROOMCREATE
  BATHROOMUPDATE
  BATHROOMDELETE
  PERMISSIONUPDATE
}

type User {
  id: ID! @id
  updatedAt: DateTime! @updatedAt
  createdAt: DateTime! @createdAt
  name: String!
  email: String! @unique
  password: String!
  resetToken: String
  resetTokenExpiry: String
  permissions: [Permission] @scalarList(strategy: RELATION)
}
```

2) I redeployed with `prisma deploy --force`

3) I deleted all my users (dev so not a huge deal)

4) I created a new user

Sadly I can still not add permissions to users.  The console shows " 1 unsaved change", but the new perm is not added

**Comment by WebRuin** [comment]
[Here is my code](https://github.com/WebRuin/Web-iPeeFreely)

**Comment by madebysid** [comment]
@WebRuin I tried the datamodel you're using (thanks for that!), and tried creating a user, with permissions, and then tried adding permissions to an existing user, but it worked both times :(

Do you see any errors in the UI after you hit `Save Changes`? Can you see if there are any requests in the DevTools Network tab that failed? I'm guessing the mutation is rejected by the server, which is why changes aren't showing up.
There should also be a log in the DevTools console which is the actual mutation string that's sent to the Prisma server. Can you send me that as well?

Also, I couldn't see a docker-compose file in the repo you've attached. Is that not committed or are you using our demo servers? If you are using Docker, why version of the Prisma image (I'm on 1.31) and connector are you using (I'm using MySQL). This is just to make sure we're on the same environment!

**Comment by WebRuin** [comment]
I am using the demo servers for now.

Here is an error I see in the console just after clicking a new permission:
```
TypeError: Cannot read property 'splice' of undefined
    at listActions.js:45
    at Object.L [as default] (immer.module.js:719)
    at i (listActions.js:43)
    at Object.t.listActions (listActions.js:33)
    at produceIF.js:27
    at Array.forEach (<anonymous>)
    at Proxy.<anonymous> (produceIF.js:13)
    at immer.module.js:398
    at Object.L [as default] (immer.module.js:723)
    at Object.t.produceIF (produceIF.js:12)
    at sagas.js:79
    at sagas.js:24
    at Object.next (sagas.js:5)
    at M (proc.js:311)
    at w (proc.js:388)
    at proc.js:699
    at N (proc.js:435)
    at M (proc.js:315)
    at w (proc.js:388)
    at proc.js:699
    at N (proc.js:435)
    at M (proc.js:315)
    at e (proc.js:270)
    at L (proc.js:554)
    at N (proc.js:435)
    at M (proc.js:315)
    at w (proc.js:388)
    at proc.js:593
    at N (proc.js:435)
    at M (proc.js:315)
    at w (proc.js:388)
    at i (proc.js:466)
    at Object.put (channel.js:73)
    at channel.js:161
    at Array.<anonymous> (channel.js:182)
    at Object.emit (channel.js:26)
    at middleware.js:67
    at dispatch (applyMiddleware.js:35)
    at utils.js:250
    at proc.js:489
    at i (scheduler.js:19)
    at s (scheduler.js:60)
    at t.a (scheduler.js:33)
    at Array.<anonymous> (channel.js:185)
    at Object.emit (channel.js:26)
    at middleware.js:67
    at i.(anonymous function) (https://app.prisma.io/static/js/main.d6268a63.js:1:2587702)
    at t.addNewItem (ListField.js:60)
    at n.onSelect (Input.js:75)
    at onClick (ListInput.js:41)
```

I am trying to add `PERMISSIONUPDATE`.  I get these after clicking `Save Changes`:
```
{data: {updateUserData_0: {id: "cjuooc4jtbsjo0b12qhl9f7z2", __typename: "User"}}}
data: {updateUserData_0: {id: "cjuooc4jtbsjo0b12qhl9f7z2", __typename: "User"}}
updateUserData_0: {id: "cjuooc4jtbsjo0b12qhl9f7z2", __typename: "User"}
id: "cjuooc4jtbsjo0b12qhl9f7z2"
__typename: "User"
```
data: {users: [{__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}],…}
count: {aggregate: {count: 1, __typename: "AggregateUser"}, __typename: "UserConnection"}
aggregate: {count: 1, __typename: "AggregateUser"}
count: 1
__typename: "AggregateUser"
__typename: "UserConnection"
users: [{__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}]
0: {__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}
email: "tim.smith.hdg@gmail.com"
id: "cjuooc4jtbsjo0b12qhl9f7z2"
name: "Tim Smith"
__id: "cjuooc4jtbsjo0b12qhl9f7z2"
__typename: "User"
```
```
 
data: {users: [{__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}],…}
count: {aggregate: {count: 1, __typename: "AggregateUser"}, __typename: "UserConnection"}
aggregate: {count: 1, __typename: "AggregateUser"}
count: 1
__typename: "AggregateUser"
__typename: "UserConnection"
users: [{__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}]
0: {__id: "cjuooc4jtbsjo0b12qhl9f7z2", name: "Tim Smith", email: "tim.smith.hdg@gmail.com",…}
email: "tim.smith.hdg@gmail.com"
id: "cjuooc4jtbsjo0b12qhl9f7z2"
name: "Tim Smith"
__id: "cjuooc4jtbsjo0b12qhl9f7z2"
__typename: "User"
```

**Comment by WebRuin** [comment]
Not sure what changed, but it is working now!  Thank you!

**Comment by madebysid** [comment]
Oh that's weird, but I'm glad this is resolved!

**Comment by mephysto** [comment]
I'd like to add that I also ran into this issue. It wasn't working on Chrome (Version 77.0.3865.120 (Official Build) (64-bit), on MacOS Catalina, adblockers were turned off).

But then I tried on Safari it did work. So added in here in case someone runs into it.

**Comment by pablopunk** [comment]
@mephysto same thing here. Chorome (Windows 10) is not working but it did work fine on Firefox

**Comment by aaronmarkle** [comment]
Adding to the list that this was not working in Chrome Version 79.0.3945.130 (Official Build) (64-bit), but worked for me when I used Safari.

**Comment by pascaloliv** [comment]
Thanks @mephysto 
Same problem here using Prisma console on app.prisma.io.

With OS: mac os 10.15.3
Chrome:  build 80.0.3987.149

It works using Safari 13.0.5. 👍

**Comment by louisotto** [comment]
Chrome 80.0.3987.163 on Mac still doesn't work.

**Comment by davizp** [comment]
I have the same issue on Chrome Version 83.0.4103.97 (Official Build) (64-bit), it works on Safari.

![prisma-error](https://user-images.githubusercontent.com/10221286/84607459-9ce15180-ae6a-11ea-8763-359326c4024b.gif)

**Comment by davizp** [comment]
I know how to fix it on Chrome. I did the following:
1. Deleted the local storage under the prisma domain (https://app.prisma.io/):
![image](https://user-images.githubusercontent.com/10221286/84607865-e29f1980-ae6c-11ea-884b-c154f0c054df.png)

2. Reload the page and it should work.

![prisma-solution](https://user-images.githubusercontent.com/10221286/84607943-4d505500-ae6d-11ea-8be6-daa9e1019cc8.gif)

**Comment by cschweipert** [comment]
This fixed it for me too!! Thanks.
